# genomes 

########################################################################################################
# Run settings - also see config/slurm.yml for slurm resource management
########################################################################################################
CORES: 16     # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")
MEMLIMIT: 120000000000  # limit in bytes
MEMLIMIT_GB: 64G        # mem limit for kallisto

GGET_RETRIES: 50    # number of retries for gget download rules

########################################################################################################
# Important directory file paths
########################################################################################################
# **Change these paths for where you want temporary (TMPDIR) and output (OUTDIR) files
#TODO: add OUTDIR to sample sheet
TMPDIR: tmp
OUTDIR: out

########################################################################################################
# Executables - file paths
########################################################################################################
# Dict of paths to all of the executables
EXEC:
  BT: bowtie
  BT2: bowtie2
  BWA: bwa
  BWA_MEM2: bwa-mem2
  GGET: gget
  K8: scripts/k8-0.2.4/k8-Linux
  KALLISTO: kallisto
  KB: kb
  MINIMAP2: minimap2
  SAMTOOLS: samtools
  STAR: /nfs/home/dmckellar/mambaforge/envs/ref_snake/bin/STAR 

# Dict of species to be included. See `resources/gget_species.txt` for options
SPECIES:
  mus_musculus
  # homo_sapiens

#TODO
CUSTOM: "sample_sheets/sample_sheet.csv"
# - columns for .fa inputs & .gtf inputs (multi-species references)
# - Add separate outputs in `rule all` for custom/gget refs?